IF OBJECT_ID('T1','U') IS NOT NULL
DROP TABLE T1
GO
IF OBJECT_ID('TEST.T2','U') IS NOT NULL
DROP TABLE TEST.T2
GO
IF SCHEMA_ID('TEST') IS NOT NULL
DROP SCHEMA TEST
GO

CREATE SCHEMA TEST
GO

CREATE TABLE T1
(
    C1 INT,
    C2 CHAR(10),
    C3 SMALLDATETIME,
    C4 NUMERIC(4,1),
)
GO

CREATE TABLE TEST.T2
(
    ID INT PRIMARY KEY NOT NULL,
    Name VARCHAR(30) NOT NULL,
    Sex NCHAR(1) CHECK(Sex = 'M' OR Sex = 'F'),
    Birthday DATE,
    UID char(64) UNIQUE,
    Tel CHAR(11)
)
GO

TRUNCATE TABLE TEST.T2
GO

INSERT INTO TEST.T2
    ([ID], [Name],Sex,Birthday,UID,Tel)
VALUES
    (1100, 'Al', 'F', '1999-8-27', 4569049, 22277779999),
    (1101, 'Be', 'F', '2001-8-12', 468764634, 00011112222),
    (1102, 'Ga', 'M', '2000-4-3', 14979956346, 00011114444)
GO

INSERT TEST.T2
    (ID,Name,Sex,Birthday,UID,Tel)
VALUES(1103, 'De', 'M', '2000-1-1', 90004604, 10088887777)
GO

UPDATE TEST.T2
    SET ID = 1104
    WHERE Name='Al'
GO

SELECT *
FROM TEST.T2
WHERE ID >= 1103 OR ID<1103
GO

IF OBJECT_ID('T2_VIEW') IS NOT NULL
DROP VIEW T2_VIEW
GO

CREATE VIEW T2_VIEW
AS
    SELECT ID, Name
    FROM TEST.T2
GO

SELECT *
FROM T2_VIEW
GO

IF OBJECT_ID('T2_NAMES') IS NOT NULL
DROP PROCEDURE T2_NAMES
GO

CREATE PROCEDURE T2_NAMES
    @ID INT
AS
BEGIN
    PRINT 'ID less than ' + CAST(@ID AS VARCHAR(10))
    SELECT ID, Name, Sex
    FROM TEST.T2
    WHERE ID < @ID
END
    GO

EXECUTE T2_NAMES 1103
GO

IF USER_ID('DESKTOP-26NRTQN\rfe') IS NOT NULL
DROP LOGIN [DESKTOP-26NRTQN\rfe]
GO

CREATE LOGIN [DESKTOP-26NRTQN\rfe]
FROM WINDOWS
WITH DEFAULT_DATABASE = [TutorialDB]
GO

IF OBJECT_ID('T1','U') IS NOT NULL
DROP TABLE T1
GO
IF OBJECT_ID('TEST.T2') IS NOT NULL
DROP TABLE TEST.T2
GO
IF SCHEMA_ID('TEST') IS NOT NULL
DROP SCHEMA TEST
GO
IF OBJECT_ID('T2_VIEW') IS NOT NULL
DROP VIEW T2_VIEW
GO
IF OBJECT_ID('T2_NAMES') IS NOT NULL
DROP PROCEDURE T2_NAMES
GO
IF SCHEMA_ID('TEST') IS NOT NULL
DROP SCHEMA TEST
GO